(()=>{
const css=`
:root{
 --sj-primary:#5B4885;--sj-main:#C8C2ED;--sj-action:#A7B8FA;--sj-accent:#EBD1DA;
 --sj-warning:#FDE7A3;--sj-normal:#BEE506;--sj-bg:#F3F4F6;--sj-info:#88AACA;
 --sj-ink:#332B4B;--sj-muted:#777184;--sj-line:#ECE8F1;--sj-surface:#FFFFFF;
 --sj-r-sm:8px;--sj-r-md:12px;--sj-r-lg:16px;--sj-space:16px;
}
*{box-sizing:border-box}html,body{background:#fff!important}body{color:var(--sj-ink)!important;letter-spacing:-.18px!important}
button,a,input,select,textarea{-webkit-tap-highlight-color:transparent}button,a{touch-action:manipulation}
button:focus-visible,a:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:3px solid rgba(167,184,250,.48)!important;outline-offset:2px!important}
.app,.wrap,.screen,.sj-navin{max-width:430px!important;margin-left:auto!important;margin-right:auto!important}
.app{padding-bottom:82px!important}.top{padding:20px 16px 7px!important}.brand,.title{color:var(--sj-primary)!important}.brand{font-size:28px!important;font-weight:900!important;letter-spacing:-1.5px!important}.tag{color:var(--sj-info)!important;font-size:10px!important;margin-top:5px!important}
.ib,.iconbtn{min-width:44px!important;min-height:44px!important;color:var(--sj-primary)!important}.searchrow{margin-top:14px!important;gap:8px!important;grid-template-columns:1fr 44px!important}.search{height:46px!important;background:#F8F7FA!important;border:1px solid #E9E5ED!important;border-radius:14px!important;padding:0 13px!important}.search input{font-size:13px!important;color:var(--sj-ink)!important}.filter,.filterbtn{width:44px!important;height:46px!important;border:1px solid #E7E2EB!important;border-radius:14px!important;background:#fff!important;color:var(--sj-primary)!important;padding:11px!important}
.locrow,.locbar{padding:8px 12px 6px 16px!important;grid-template-columns:minmax(0,1fr) 38px!important}.locs,.locations{gap:7px!important}.locs button,.locations button{height:34px!important;min-height:34px!important;padding:0 14px!important;border-radius:18px!important;border:1px solid #E5E0E9!important;background:#fff!important;color:#625B70!important;font-size:11px!important;white-space:nowrap!important}.locs button.on,.locations button.on{background:var(--sj-primary)!important;border-color:var(--sj-primary)!important;color:#fff!important;font-weight:800!important}.locmanage,.locManage{width:36px!important;height:34px!important;border-radius:11px!important;background:#fff!important;color:var(--sj-primary)!important}
.stats{padding:9px 16px 11px!important;gap:12px!important;font-size:11px!important;border-bottom:1px solid #F1EEF3!important;overflow:auto!important;white-space:nowrap!important}.section,.sectionTitle{padding:14px 16px 7px!important;font-size:13px!important}.list{padding:4px 12px 16px!important}
.card{grid-template-columns:64px minmax(0,1fr) 52px!important;gap:10px!important;min-height:112px!important;border-radius:var(--sj-r-lg)!important;padding:11px!important;margin-bottom:9px!important;border:1px solid var(--sj-line)!important;box-shadow:0 2px 10px rgba(91,72,133,.035)!important;background:#fff!important}.card.using{background:#FCFBFF!important;border-color:#DDD5ED!important}.thumb{width:64px!important;height:64px!important;border-radius:12px!important;background:#F7F4FA!important}.thumb img{object-fit:contain!important}.placeholder{width:38px!important;height:38px!important}.info{padding-top:0!important;min-width:0!important}.name{font-size:14px!important;line-height:1.3!important;color:var(--sj-ink)!important;font-weight:800!important;white-space:normal!important;display:-webkit-box!important;-webkit-line-clamp:2!important;-webkit-box-orient:vertical!important;overflow:hidden!important}.meta,.expiry,.exp{font-size:10.5px!important;line-height:1.35!important;margin-top:3px!important;color:var(--sj-muted)!important}.chips,.lower{margin-top:6px!important;gap:4px!important}.chip,.badge{font-size:9.5px!important;padding:3px 7px!important;border-radius:8px!important}.side{align-self:center!important}.qty,.qtynum{font-size:26px!important;color:var(--sj-primary)!important;font-weight:900!important}.unit,.qtyunit{font-size:9px!important}.edit{right:8px!important;bottom:7px!important;min-width:44px!important;height:30px!important;padding:0 9px!important;border-radius:9px!important;border:1px solid #E0DAE8!important;color:var(--sj-primary)!important;background:#fff!important;font-size:10px!important}.edit svg{width:12px!important}
.empty{text-align:center!important;padding:64px 24px!important;color:#918A9A!important;font-size:13px!important;line-height:1.7!important}
.screen{padding:8px 16px 92px!important}.screenhead{height:56px!important;margin-bottom:18px!important;border-bottom:0!important}.screenhead h2{font-size:19px!important;color:#302568!important;font-weight:850!important}.back,.trash{min-width:44px!important;min-height:44px!important;color:var(--sj-primary)!important}.field{margin-bottom:14px!important}.field label{font-size:12px!important;color:#6F687C!important;margin-bottom:6px!important;font-weight:650!important}.field input,.field select,.field textarea,.datebtn,.dateTrigger{min-height:46px!important;border-radius:11px!important;border:1px solid #DED9E5!important;background:#fff!important;font-size:13px!important;padding-left:12px!important;padding-right:12px!important}.field textarea{height:76px!important;padding-top:11px!important}.g2,.grid2{gap:9px!important}.quick{gap:6px!important}.quick button{min-width:38px!important;height:38px!important;border-radius:9px!important;font-size:12px!important}.quick button.on,.months button.on{background:var(--sj-primary)!important;color:#fff!important}.hint{font-size:10px!important;line-height:1.5!important}.actions{gap:9px!important;margin-top:20px!important}.actions button,.save,.calendarDone{height:50px!important;border-radius:12px!important;font-size:14px!important}.primary,.save,.calendarDone{background:var(--sj-primary)!important;color:#fff!important}.sj-danger-zone{margin-top:28px!important;padding-top:18px!important;border-top:1px solid var(--sj-line)!important}.sj-danger-zone button{width:100%!important;height:48px!important;border:1px solid #EBD1DA!important;border-radius:12px!important;background:#FFF8FA!important;color:#B94E62!important;font-weight:750!important}
.nav,.sj-nav{background:#fff!important;border-top:1px solid #ECE8F0!important;box-shadow:0 -2px 12px rgba(56,43,85,.035)!important}.navin,.sj-navin{grid-template-columns:repeat(5,1fr)!important}.nav a,.nav button,.sj-nav a,.sj-nav button{height:68px!important;min-width:0!important;background:#fff!important;border:0!important;color:#918B99!important;font-size:9.5px!important;gap:3px!important;text-decoration:none!important}.nav .on,.nav .active,.sj-nav .active{color:var(--sj-primary)!important;font-weight:850!important}.nav svg,.sj-nav svg{width:23px!important;height:23px!important}
@media(max-width:360px){.card{grid-template-columns:58px minmax(0,1fr) 46px!important;padding:9px!important}.thumb{width:58px!important;height:58px!important}.name{font-size:13px!important}.qty,.qtynum{font-size:23px!important}.nav a,.nav button,.sj-nav a,.sj-nav button{font-size:8.5px!important}}
`;
function installCSS(){let old=document.getElementById('sj-design-v30');if(old)old.remove();const s=document.createElement('style');s.id='sj-design-v30';s.textContent=css;document.head.appendChild(s)}
function settingsNav(){const nav=document.querySelector('.nav .navin');if(!nav||nav.querySelector('[data-sj-settings]'))return;const b=document.createElement('button');b.type='button';b.dataset.sjSettings='1';b.setAttribute('aria-label','설정');b.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.1A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.1A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.1A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.14.37.36.7.66.96.3.25.67.4 1.06.44H21v4h-.1a1.7 1.7 0 0 0-1.5.6Z"/></svg><span>설정</span>';b.onclick=()=>{const top=document.querySelector('#settings');if(top){top.click();return}const modal=document.querySelector('#settingsModal');if(modal)modal.classList.add('open')};nav.appendChild(b)}
function polishInventory(){const q=document.querySelector('#q');if(q)q.placeholder='제품명, 브랜드, 별칭을 검색하세요.';document.querySelectorAll('.stats').forEach(el=>{el.innerHTML=el.innerHTML.replaceAll('재고 부족','품절')})}
function polishEdit(){const form=document.querySelector('#form');if(!form)return;const title=form.querySelector('#formTitle');const del=form.querySelector('#del');if(!del)return;const editing=title&&title.textContent.includes('수정');if(editing){del.style.display='none';if(!form.querySelector('.sj-danger-zone')){const zone=document.createElement('div');zone.className='sj-danger-zone';const b=document.createElement('button');b.type='button';b.textContent='이 제품 삭제';b.onclick=()=>del.click();zone.appendChild(b);const screen=form.querySelector('.screen');if(screen)screen.appendChild(zone)}}else{del.style.display='none';form.querySelector('.sj-danger-zone')?.remove()}}
function polish(){settingsNav();polishInventory();polishEdit()}
installCSS();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',polish);else polish();new MutationObserver(()=>requestAnimationFrame(polish)).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
})();